// src/features/hchanh/api.js — API riêng cho feature Hành chánh.
// Hiện tại dùng lại client legacy trong src/api.js để refactor theo từng bước an toàn.

import {
  getHchanh_Index,
  syncHchanh,
  getHchanh_Dashboard,
  getHchanh_VtytDraft,
  saveHchanh_VtytDraft,
  clearHchanh_VtytDraft,
  getHchanh_Patient,
  fetchHchanh,
  getHchanh_Tickets,
  createHchanh_Ticket,
  updateHchanh_Ticket,
  createHchanh_Snapshot,
  getHchanh_Snapshot,
  clearHchanh_Patient,
  clearHchanh,
  rescanHchanh,
  openHchanh_BedEdit,
  printHchanh_BillingPdf,
  downloadHchanh_BillingPdf,
  printHchanh_Ticket,
  exportHchanh_Issues,
  previewInputVTYT,
  runInputVTYT,
} from '../../api.js';

export const hchanhApi = {
  getIndex: getHchanh_Index,
  sync: syncHchanh,
  getDashboard: getHchanh_Dashboard,
  getVtytDraft: getHchanh_VtytDraft,
  saveVtytDraft: saveHchanh_VtytDraft,
  clearVtytDraft: clearHchanh_VtytDraft,
  getPatient: getHchanh_Patient,
  fetchPatient: fetchHchanh,
  getTickets: getHchanh_Tickets,
  createTicket: createHchanh_Ticket,
  updateTicket: updateHchanh_Ticket,
  createSnapshot: createHchanh_Snapshot,
  getSnapshot: getHchanh_Snapshot,
  clearPatient: clearHchanh_Patient,
  clearAll: clearHchanh,
  rescan: rescanHchanh,
  openBedEdit: openHchanh_BedEdit,
  printBillingPdf: printHchanh_BillingPdf,
  downloadBillingPdf: downloadHchanh_BillingPdf,
  printTicket: printHchanh_Ticket,
  exportIssues: exportHchanh_Issues,
  previewInputVTYT,
  runInputVTYT,
};

export {
  getHchanh_Index,
  syncHchanh,
  getHchanh_Dashboard,
  getHchanh_VtytDraft,
  saveHchanh_VtytDraft,
  clearHchanh_VtytDraft,
  getHchanh_Patient,
  fetchHchanh,
  getHchanh_Tickets,
  createHchanh_Ticket,
  updateHchanh_Ticket,
  createHchanh_Snapshot,
  getHchanh_Snapshot,
  clearHchanh_Patient,
  clearHchanh,
  rescanHchanh,
  openHchanh_BedEdit,
  printHchanh_BillingPdf,
  downloadHchanh_BillingPdf,
  printHchanh_Ticket,
  exportHchanh_Issues,
  previewInputVTYT,
  runInputVTYT,
};
